services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: py-app
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy  # ← Ждет healthcheck
  nginx:
    container_name: py-app-proxy
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nging.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
  postgres:
    container_name: py-app-db
    image: postgres:18
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql  # ← Изменен путь
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d myapp"]
      interval: 2s
      timeout: 5s
      retries: 10
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python -m bot.main
    env_file: .env
    depends_on:
      - app
      - postgres
    volumes:
    - .:/app
    
volumes:
  postgres_data:
    