version: "3.8"

services:
  app:
    image: 192.168.0.240:6000/my-python-app-app:latest
    # container_name: py-app
    ports:
      - "5000:5000"
    depends_on:
      - postgres # condition: service_healthy  # ← Ждет healthcheck
    deploy:
      replicas: 1
  nginx:
    # container_name: py-app-proxy
    image: 192.168.0.240:6000/my-nginx:latest
    ports:
      - "8080:80"
    # volumes:
    #   - ./nging.conf:/etc/nginx/conf.d/default.conf:ro
    deploy:
      replicas: 3
    depends_on:
      - app
  postgres:
    # container_name: py-app-db
    image: postgres:18
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql  # ← Изменен путь
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d myapp"]
      interval: 2s
      timeout: 5s
      retries: 10
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == debianServer  # ← Только debianServer!
  bot:
    image: 192.168.0.240:6000/my-python-app-bot:latest
    command: python -m bot.main
    env_file: .env
    depends_on:
      - app
      - postgres
    # volumes:
    #   - .:/app
    deploy:
      replicas: 1

    
volumes:
  postgres_data:
    driver: local
    